### ISSUE TITLE
Question regarding this error

### ISSUE THREAD

**Issue by dedalusMohantyMa** [lobovkin/forwarddomain.net#1]
Hi
I used your tool, which is a pretty nice service.
But recently I got this error `forward-domain= TXT is missing` despite having a TXT entry at my registrar. Do you know, what is missing?
I only copied it from your generator and pasted it in. the value of the TXT entry has been `TXT=https://someurl.com/path/to/*`
Thanks for the advice.

**Comment by willnode** [comment]
Check if it's working on Google DNS. For example, I have set `r.forwarddomain.net` redirects to `forwarddomain.net` by putting a TXT record to `_.r.forwarddomain.net` (the underscore is essential)

Check it here: https://dns.google/query?name=_.r.forwarddomain.net&rr_type=TXT&ecs=

**Comment by dedalusMohantyMa** [comment]
I see, then I understand. Thx a lot.
